name: AWS Deploy / Production

on:
  workflow_dispatch:

jobs:
  deploy-production:
    name: Deploy / Production
    uses: ./.github/workflows/.deploy-aws.yml
    with:
      environment: production
      image_tag_suffix: '-prod'
    secrets: inherit
