name: AWS Deploy / Production

on:
  workflow_dispatch:

jobs:
  deploy-production:
    name: Deploy / Production
    uses: threatzero-solutions/github-workflows/.github/workflows/deploy-aws.yml@main
    with:
      environment: production
      image_tag_suffix: '-prod'
    secrets: inherit
