name: AWS Deploy / Staging

on:
  push:
    branches: ['main']

jobs:
  deploy-staging:
    name: Deploy / Staging
    uses: ./.github/workflows/.deploy-aws.yml
    with:
      environment: staging
    secrets: inherit
