name: AWS Deploy / Staging

on:
  push:
    branches: ['main']

jobs:
  deploy-staging:
    name: Deploy / Staging
    uses: threatzero-solutions/github-workflows/.github/workflows/deploy-aws.yml@main
    with:
      environment: staging
    secrets: inherit
